language: python

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    packages:
      - libjson-c-dev

install:
  - pip install --upgrade pip setuptools wheel
  - pip install autopep8
  - python setup.py develop

script:
  # check python format
  - autopep8 -r . --diff --exit-code

  # check game_manager.py
  - python autogames/test/check_game_manager.py

  # check server.py and client.py
  - ./autogames/test/check_server_and_client.sh

  # check games
  # tictactoe
  - python autogames/test/games/tictactoe/check_tictactoe_game.py
  - ./autogames/test/games/tictactoe/check_tictactoe_with_clients.sh
  # othello
  - python autogames/test/games/othello/check_othello_game.py
  - ./autogames/test/games/othello/check_othello_with_clients.sh

  # check clients of each language
  # C
  - ./autogames/test/c/check_c_compile.sh
  - ./autogames/test/c/check_c_clients.sh

sudo: false
