language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install autopep8

script:
  # check python format
  - autopep8 -r . --diff --exit-code
  # check if game works correctly
  - python tictactoe/test/check_tictactoe.py

sudo: false
