language: python

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    packages:
      - libjson-c-dev

install:
  - pip install --upgrade pip setuptools wheel
  - pip install autopep8
  - python setup.py develop

script:
  # check python format
  - autopep8 -r . --diff --exit-code
  # check if game works correctly
  - python autogames/test/check_tictactoe.py
  # check if player_manager works correctly
  - python autogames/test/check_game_manager.py
  # check if C client program can be compiled
  - ./autogames/test/check_c_compile.sh
  # check if server and client works correctly
  - ./autogames/test/check_server_and_client.sh
  # check if othello game with server and client works correctly
  - ./autogames/test/check_othello_server.sh

sudo: false
